.Dd June 9, 2015
.Dt SPLIT 1
.Os split
.Sh NAME
.Nm split
.Nd a windowmanager brutally ripped into little pieces.
.Sh DESCRIPTION
.Nm
It's the dead carcass of a wm.
.Sh COMMANDS
.Bl -tag -width Ds -offset 60
.It chwb
change window's border
.It chwso
change window's stacking order
.It ignw
ignore/unignore window
.It wkill
kill windows
.It lw
list windows
.It mapw
map/unmap windows
.It fw
print focused window
.It wattr
show window's attributes
.It mvm
move the mouse pointer
.It mvw
move a window
.It rsw
resize a window
.It twf
focus a window
.It wtp
teleport a window
.El
.Sh ENVIRONMENT
.Nm
acts on the X display specified by the
.Ev DISPLAY
variable.
.Sh SEE ALSO
.Xr lw 1 ,
.Xr wf 1 ,
.Xr bw 1 ,
.Xr kw 1 ,
.Xr hw 1 ,
.Xr aw 1 ,
.Xr mw 1 ,
.Xr rw 1 ,
